---
- name: get Telegraf package
  get_url: url=http://get.influxdb.org/telegraf/telegraf_0.1.8_amd64.deb dest=/root/telegraf_0.1.8_amd64.deb
  when: ansible_os_family == "Debian"

- name: install Telegraf package
  apt: deb=/root/telegraf_0.1.8_amd64.deb
  when: ansible_os_family == "Debian"
